# Generated by Django 5.0.6 on 2024-08-03 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='summary',
            new_name='title',
        ),
    ]
